### ISSUE TITLE
Unable to get this working.

### ISSUE THREAD

**Issue by nerd190** [jakobrs/nix-termux#1]
THANK YOU FOR THIS! I have been trying hard for a while to get nix pkg manager in Termux.
ReadMe is very brief, after performing the 2 commands it doesnt work, after reading the script I tried running `start` with no args which put me "in proot", still unable to execute "nix" commands, please help! thank you!

**Comment by jakobrs** [comment]
You probably need to add `-L` to `curl`:

```bash
./start sh <(curl -L 'https://nixos.org/nix/install')
```

This was changed a while ago and I hadn't updated the readme since. It's updated now.

**Comment by nerd190** [comment]
Works perfectly thank you so much! I appreciate it, I tried myself to achieve this and for the last few days... failed.
Your linux-fu is stronger than mine! :)
P.S as nix is amazing and this is currently the only working method, perhaps post this in the Termux Reddit? I am sure they would like it too. [r/termux](https://reddit.com/r/termux)
Just a suggestion. THANK YOU AGAIN!
