### ISSUE TITLE
(question - no bug) How to use nix binaries in Termux.

### ISSUE THREAD

**Issue by nerd190** [jakobrs/nix-termux#2]
Hello again! :)
I would like to compile binaries in Nix, then use them out of proot in Termux.
I have tried copying the binary (from .nix-profile/bin) to somewhere on my PATH in Termux (.local/bin) but once I exit proot, I cannot use the binary, it shows that its there, but when calling it I get an error ("no such file or directory")
I was wondering if its possible? or will the binaries only ever work in proot?
**THANK YOU FOR THIS! ITS APPRECIATED!**

**Comment by jakobrs** [comment]
Dynamically-linked binaries won't be able to find the interpreter (ld.so) or its dependencies outside the chroot, so no, you can not copy the binaries outside of the chroot and use them directly.

However, you can use the `./launch-program` script I've added as a workaround, see [here](https://github.com/jakobrs/nix-termux#making-installed-programs-available-outside-the-chroot). Remember to update nix-termux first though:

```bash
cd /path/to/nix-termux

git pull

**Comment by nerd190** [comment]
Thank you!! once calling the binary outside of proot, I got:
```
~
 ❯ highlight --help
/data/data/com.termux/files/home/.local/bin/highlight: line 6: /data/data/com.termux/files/home/.local/bin/start: No such file or directory
```
So I then copied `nix-termux/start` to `.local/bin` but still get an error:
```
~
❯ highlight --help
proot error: '~/.nix-profile/bin/highlight' not found (root = /, cwd = /data/data/com.termux/files/home, $PATH=(null))
```

Thank you once again for all your time and efforts!

**Comment by jakobrs** [comment]
Well that's what I get for not testing anything. I've pushed another fix.

Run the following to fix it:
```bash
# Update
cd /path/to/nix-termux
git pull

# Remove ~/.local/bin/start, which isn't supposed to be there
rm ~/.local/bin/start
```

**Comment by nerd190** [comment]
Sorry for the delayed response,
I confirm that this works perfectly and its **incredibly useful!**
You have done amazing with this project!
Once again, thank you so much, its really appreciated!
Closing the issue.
